# Generated by Django 4.2.1 on 2023-05-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkling', '0002_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(to='inkling.document'),
        ),
    ]
