# Generated by Django 4.2.1 on 2023-05-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkling', '0005_alter_document_project_name_alter_project_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='documents',
        ),
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(to='inkling.document'),
        ),
    ]
