# Generated by Django 4.2.1 on 2023-05-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkling', '0010_alter_project_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='documents',
        ),
    ]
