# Generated by Django 4.2.1 on 2023-05-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkling', '0013_remove_project_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(to='inkling.document'),
        ),
    ]
