# Generated by Django 4.2.1 on 2023-05-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkling', '0016_remove_project_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='project_name',
            new_name='project',
        ),
    ]
