# Generated by Django 4.2.1 on 2023-05-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkling', '0017_rename_project_name_document_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.CharField(default=''),
        ),
    ]
